[tool.poetry]
name = "fddfsa"
version = "1.0"
authors = ["hefdfsafda", "dsafdas"]
description = "stuff"

[tool.poetry.dependencies]
python = "^3.8"
wandb = "0.16.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"